language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - net-tools
      - mplayer
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt
before_script:
  - mkdir -p ~/.screenly ~/.config/uzbl/
  - cp ansible/roles/screenly/files/uzbl-config ~/.config/uzbl/config-screenly
  - cp ansible/roles/screenly/files/screenly.conf ~/.screenly/
  - cp ansible/roles/screenly/files/screenly.db ~/.screenly/
  - echo -e "[local]\nlocalhost ansible_connection=local" > ansible/localhost
  - curl http://orig04.deviantart.net/7f89/f/2016/173/7/0/ussr_tyan_by_kawaielli-da76ghz.jpg > /tmp/image.jpg
  - curl https://www.screenly.io/upload/ose_tests/little_buck_bunny_trailer_480p.mov > /tmp/video.mov
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - python server.py &
  - sleep 3 # give xvfb some time to start
script:
  - find . -name \*.py -exec pep8 --ignore=E402,E501,E731 {} +
  - nosetests -v -a '!fixme' --with-isolation
  - ansible-playbook --syntax-check -i ansible/localhost ansible/site.yml
sudo: false
